class APIs:
    RE_USERNAME = Pipes.re_expression(Consts.RE_USERNAME, 'args.1', '用户名格式错误!')
    RE_UUID = Pipes.re_expression(Consts.RE_UUID, 'args.1', 'UUID 格式错误!')
    RE_QQNUMBER = Pipes.re_expression(Consts.RE_QQNUMBER, 'args.1', 'QQ 号码格式错误!')
    RE_GUILDNAME = Pipes.re_expression(Consts.RE_GUILDNAME, 'guild.name', '公会名格式错误!')
    MOJANG_PROFILE = Pipes.api('mojang_profile', None, 'id', 'args.1')
    MOJANG_SESSION_NAME = Pipes.api('mojang_session', None, 'id', 'api_mojang_profile.id')
    MOJANG_SESSION_UUID = Pipes.api('mojang_session', None, 'id', 'args.1')
    MOJANG_SESSION_HYPIXEL_API = Pipes.api('mojang_session', None, 'id', 'api_hypixel_key.record.owner')
    MOJANG_SESSION_HYPIXEL_GUILDNAME = Pipes.api('mojang_session', None, 'id', 'guild.player.uuid')
    HYPIXEL_API = Pipes.api('hypixel_key', 'success', 'record', 'apiset.hypixel_apikey')
    HYPIXEL_PUNISHMENTSTATS = Pipes.api('hypixel_punishmentstats', 'success', 'staff_total', 'apiset.hypixel_apikey')
    HYPIXEL_PLAYER = Pipes.api('hypixel_player', 'success', 'player', 'apiset.hypixel_apikey', 'api_mojang_profile.id')
    HYPIXEL_GUILD_NAME = Pipes.api('hypixel_guild_name', 'success', 'guild', 'apiset.hypixel_apikey', 'guild.name')
    HYPIXEL_GUILD_PLAYER = Pipes.api('hypixel_guild_player', 'success', 'guild', 'apiset.hypixel_apikey',
                                     'api_mojang_profile.id')
    ANTISNIPER_DENICK = Pipes.api('antisniper_denick', 'success', 'player.ign', 'apiset.antisniper_apikey', 'args.1')
    ANTISNIPER_FINDNICK = Pipes.api('antisniper_findnick', 'success', 'player.ign', 'apiset.antisniper_apikey',
                                    'args.1')
    ANTISNIPER_WINSTREAK = Pipes.api('antisniper_winstreak', 'success', 'player.ign', 'apiset.antisniper_apikey',
                                     'args.1')
    OPTIFINE_CAPE = Pipes.api_binary('optifine_cape', 'api_mojang_profile.name')
    OPTIFINE_BANNER = Pipes.api_binary('optifine_banner', 'ofcape.url', 'ofcape.valign')
    OPTIFINE_FORMAT = Pipes.api_optifine_format()
    QQAPI_QQAPI = Pipes.api('qqapi_qqapi', None, 'qq', 'args.1')